/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vendas;

import java.sql.Connection;
import java.util.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author David
 */
public class FormPagamento extends javax.swing.JFrame {
    int forma;
    double valor;
    double pago;
    double troco;
    String cliente, funcionario;
    String strTroco;
    Date data = new Date();
    private String usuario = "root", senha = "toor", porta = "3306" , servidor = "localhost", nomeBanco = "livrarialabeng";
    private Connection conexao=null;
    private ResultSet rs=null;
    private Statement stm=null;
    Vector item;
    

    /**
     * Creates new form FormPagamento
     * @param forma
     * @param valor
     * @param cli
     * @param itens
     * @param fun
     */
    public FormPagamento(int forma, double valor, String cli, String fun,Vector itens) {
        this.data.getDate();
        this.forma = forma;
        this.valor = valor;
        this.cliente = cli;
        this.funcionario = fun;
        this.item= itens;
        
        initComponents();
        
         if (forma == 2){
            pago = valor;
            troco = Integer.parseInt(txtPago.getText()) - valor;
            txtPago.setEditable(false);
            txtPago.setText(String.valueOf(troco));
         }
        txtTotal.setText(String.valueOf(valor));
       
    }
    
    /**
     *
     */
    public void conexaoBD(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            
        } catch (ClassNotFoundException ex) {
            System.out.println(ex);
        }
      
        try{
            
            String strCon = "jdbc:mysql://"+servidor+":"+porta+"/"+nomeBanco;
            conexao = DriverManager.getConnection(strCon, usuario, senha);
        }
        catch(Exception ee){
            System.out.println(ee);
            
        }
    }

    /**
     *
     */
    public FormPagamento() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPago = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTroco = new javax.swing.JTextField();
        btnFinalizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Total:");

        txtTotal.setEditable(false);
        txtTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel2.setText("Pago:");

        txtPago.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPago.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPagoFocusLost(evt);
            }
        });

        jLabel3.setText("Troco:");

        txtTroco.setEditable(false);
        txtTroco.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        btnFinalizar.setText("Finalizar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPago))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFinalizar)
                            .addComponent(txtTroco))))
                .addContainerGap(239, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTroco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(btnFinalizar)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPagoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPagoFocusLost
        // TODO add your handling code here:
         if(Double.parseDouble(txtPago.getText())< valor){
             JOptionPane.showMessageDialog(null,"Erro! Valor invalidado.");
         }
         troco = Double.parseDouble(txtPago.getText()) - valor;
         txtTroco.setText(String.valueOf(troco));
    }//GEN-LAST:event_txtPagoFocusLost

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        // TODO add your handling code here:
        String sql= null;
        try {
            conexaoBD();
            sql = "INSERT INTO venda(CodCliente, CodFuncionario, valor, data) VALUES ("+cliente+","+funcionario+","+valor+", NOW())";
            stm = conexao.createStatement();
            stm.execute(sql);
            for(Object x: item){
                    sql = "UPDATE livro SET qtd = (qtd-1) where CodLivro = " + (String)x;
                    stm = conexao.createStatement();
                    stm.execute(sql);
                }
            conexao.close();
            JOptionPane.showMessageDialog(null,"Gravado com sucesso!");
        } catch (SQLException ex) {
            System.out.println(ex + sql);
            JOptionPane.showMessageDialog(null,"Erro ao gravar!");
    }//GEN-LAST:event_btnFinalizarActionPerformed
    }
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtPago;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTroco;
    // End of variables declaration//GEN-END:variables
}
