/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Consulta;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author david
 */
public class FormPesquisa extends javax.swing.JFrame {
    private String usuario = "root", senha = "toor", porta = "3306" , servidor = "localhost", nomeBanco = "livrarialabeng";
    private Connection conexao=null;
    private ResultSet rs=null;
    private Statement stm=null;
    private int cod;
    private JTable table;

   /*
     * Creates new form FormPesquisa
     */
    public FormPesquisa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPesquisa = new javax.swing.JTextField();
        cbmPesquisa = new javax.swing.JComboBox();
        btPesquisar = new javax.swing.JButton();
        spResultado = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Livraria -Pesquisa-");
        setBounds(new java.awt.Rectangle(0, 0, 1000, 700));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        cbmPesquisa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Titulo", "Autor", "Editora", "Categoria" }));

        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spResultado)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbmPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbmPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addGap(119, 119, 119))
        );

        setSize(new java.awt.Dimension(1000, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        // TODO add your handling code here:
        rs=null;
        String sql;
        if(cbmPesquisa.getSelectedItem()=="Autor")
            sql= "Select * from livro where autor like '%"+txtPesquisa.getText()+"%'";
        else if(cbmPesquisa.getSelectedItem()=="Titulo")
            sql= "Select * from livro where titulo like '%"+txtPesquisa.getText()+"%'";
            else if(cbmPesquisa.getSelectedItem()=="Categoria")
                    sql= "Select * from livro where categoria like '%"+txtPesquisa.getText()+"%'";
                else
                    sql= "Select * from livro where editora like '%"+txtPesquisa.getText()+"%'";
        System.out.println(sql);
        try{
            conexaoBD();
            stm = conexao.createStatement();
            rs = stm.executeQuery(sql);
        }catch(SQLException ex){
            
        }
        montaTabela();       
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.dispose();
       
    }//GEN-LAST:event_formWindowClosing
    private void montaTabela(){
            try{
                DefaultTableModel tableMode1 = new DefaultTableModel(
                        new String[]{},0){ };
                int qtdColunas = rs.getMetaData().getColumnCount();
                for(int indice=1; indice<=qtdColunas; indice ++)
                    tableMode1.addColumn(rs.getMetaData().getColumnName(indice));

                table = new JTable(tableMode1);
                DefaultTableModel dtm= (DefaultTableModel) table.getModel();

                while(rs.next()){
                    try{
                        String[] dados = new String[qtdColunas];
                        for(int i= 1; i<=qtdColunas; i++){
                            dados[i-1] =rs.getString(i);
                        }
                        dtm.addRow(dados);
                        spResultado.setViewportView(table);
                        spResultado.enableInputMethods(false);
                    }catch(Exception ef){
                        System.out.println("Erro ao montar linha!");
                    }
                }
            }catch(Exception ee){
                System.out.println("Erro ao montar tabela!--"+ee);
            }
            table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt){
             tabelaMouseClicked(evt);
         }
      });
    }
    private void tabelaMouseClicked(java.awt.event.MouseEvent evt){
       
      }
    /**
     * Conecta ao banco de dados!
     */
    public void conexaoBD(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            
        } catch (ClassNotFoundException ex) {
            System.out.println(ex);
        }
      
        try{
            
            String strCon = "jdbc:mysql://"+servidor+":"+porta+"/"+nomeBanco;
            conexao = DriverManager.getConnection(strCon, usuario, senha);
        }
        catch(Exception ee){
            System.out.println(ee);
            
        }
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btPesquisar;
    private javax.swing.JComboBox cbmPesquisa;
    private javax.swing.JScrollPane spResultado;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
